services:
  nginx:
    image: nginx:stable-alpine
    container_name: simplipay-nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db
    networks:
      - app-network

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: simplipay-php
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/simplipay
    networks:
      - app-network
  
  db:
    image: mysql:8.0.26
    container_name: simplipay-db
    ports:
      - "25483:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: simplipay
      MYSQL_USER: simplipay
      MYSQL_PASSWORD: simplipay
    restart: always
    networks:
      - app-network

networks:
  app-network: